


list1=["Tomato","Black Gram (Urd Beans)(Whole)",
                  "Lemon",
                  "Jowar(Sorghum)",
                  "Bengal Gram(Gram)(Whole)",
                  "Paddy(Dhan)(Common)",
                  "Maize",
                  "Apple",
                  "Banana - Green",
                  "Bhindi(Ladies Finger)",
                  "Bitter Gourd",
                  "Bottle Gourd",
                  "Brinjal",
                  "Cabbage",
                  "Capsicum",
                  "Carrot",
                  "Cauliflower",
                  "Chikoos(Sapota)",
                  "Coriander(Leaves)",
                  "Cucumbar(Kheera)",
                  "Garlic",
                  "Ginger(Green)",
                  "Grapes",
                  "Green Chilli",
                  "Guar",
                  "Karbuja(Musk Melon)",
                  "Knool Khol",
                  "Little Gourd (Kundru)",
                  "Methi(Leaves)",
                  "Mousambi(Sweet Lime)",
                  "Onion",
                  "Orange",
                  "Papaya (Raw)",
                  "Peas Wet",
                  "Pomegranate",
                  "Potato",
                  "Pumpkin",
                  "Raddish",
                  "Sweet Potato",
                  "Tinda",
                  "Water Melon",
                  "Soyabean",
                  "Cotton",
                  "Cummin Seed(Jeera)",
                  "Groundnut",
                  "Sesamum(Sesame",
                  "Gingelly",
                  "Til)",
                  "Wheat",
                  "Arhar (Tur/Red Gram)(Whole)",
                  "Bajra(Pearl Millet/Cumbu)",
                  "Green Gram (Moong)(Whole)",
                  "Kabuli Chana(Chickpeas-White)",
                  "Methi Seeds",
                  "Mustard",
                  "Castor Seed",
                  "Guar Seed(Cluster Beans Seed)",
                  "Isabgul (Psyllium)",
                  "Onion Green",
                  "Corriander Seed",
                  "Dry Chillies",
                  "Ground Nut Seed",
                  "Cluster Beans",
                  "Beetroot",
                  "Cowpea(Veg)",
                  "Drumstick",
                  "Elephant Yam (Suran)",
                  "French Beans (Frasbean)",
                  "Indian Beans (Seam)",
                  "Pegeon Pea (Arhar Fali)",
                  "Pointed Gourd (Parval)",
                  "Ridge Gourd(Tori)",
                  "Surat Beans (Papadi)",
                  "Turmeric (Raw)",
                  "Yam (Ratalu)",
                  "Spinach",
                  "Banana",
                  "Ber(Zizyphus/Borehannu)",
                  "Ginger(Dry)",
                  "Guava",
                  "Kinnow",
                  "Turnip",
                  "Leafy Vegetable",
                  "Papaya",
                  "Peas Cod",
                  "Pineapple",
                  "Mashrooms",
                  "Colacasia",
                  "Field Pea",
                  "Dalda",
                  "Mahua",
                  "Mustard Oil",
                  "Rice",
                  "Sugar",
                  "Wheat Atta",
                  "White Peas",
                  "Beans",
                  "Chapparad Avare",
                  "Chilly Capsicum",
                  "Green Avare (w)",
                  "Seemebadnekai",
                  "Snake Gourd",
                  "Suvarna Gadde",
                  "Sweet Pumpkin",
                  "Kulthi(Horse Gram)",
                  "Bunch Beans",
                  "Thondekai",
                  "Tamarind Seed",
                  "Tamarind Fruit",
                  "Tender Coconut",
                  "Foxtail Millet(Navane)",
                  "Green Peas",
                  "Tapioca",
                  "Amphophalus",
                  "Ashgourd",
                  "Amaranthus",
                  "Mango",
                  "Black Pepper",
                  "Mango (Raw-Ripe)",
                  "Coconut",
                  "Rubber",
                  "Copra",
                  "Coconut Oil",
                  "Coconut Seed",
                  "Cowpea (Lobia/Karamani)",
                  "Lime",
                  "Pepper Ungarbled",
                  "Duster Beans",
                  "Coffee",
                  "Mint(Pudina)",
                  "Gur(Jaggery)",
                  "Chrysanthemum(Loose)",
                  "Marigold(Calcutta)",
                  "Betal Leaves",
                  "Hen",
                  "Jack Fruit",
                  "Fish",
                  "Amla(Nelli Kai)",
                  "Rat Tail Radish (Mogari)",
                  "Season Leaves",
                  "Squash(Chappal Kadoo)",
                  "Moath Dal",
                  "Taramira",
                  "Barley (Jau)",
                  "Soanf",
                  "Cashewnuts",
                  "T.v. Cumbu",
                  "Turmeric",
                  "Ragi (Finger Millet)",
                  "Paddy(Dhan)(Basmati)",
                  "Arhar Dal(Tur Dal)",
                  "Bengal Gram Dal (Chana Dal)",
                  "Black Gram Dal (Urd Dal)",
                  "Green Gram Dal (Moong Dal)",
                  "Lentil (Masur)(Whole)",
                  "Masur Dal",
                  "Ghee",
                  "Peas(Dry)",
                  "Linseed",
                  "Jute",
                  "Tomato",
                  "Tomato",
                  "Black Gram (Urd Beans)(Whole)",
                  "Lemon",
                  "Jowar(Sorghum)",
                  "Bengal Gram(Gram)(Whole)",
                  "Paddy(Dhan)(Common)",
                  "Maize",
                  "Apple",
                  "Banana - Green",
                  "Bhindi(Ladies Finger)",
                  "Bitter Gourd",
                  "Bottle Gourd",
                  "Brinjal",
                  "Cabbage",
                  "Capsicum",
                  "Carrot",
                  "Cauliflower",
                  "Chikoos(Sapota)",
                  "Coriander(Leaves)",
                  "Cucumbar(Kheera)",
                  "Garlic",
                  "Ginger(Green)",
                  "Grapes",
                  "Green Chilli",
                  "",
                  "Karbuja(Musk Melon)",
                  " Khol",
                  "Little Gourd (Kundru)",
                  "Methi(Leaves)",
                  "Mousambi(Sweet Lime)",
                  "Onion",
                  "Orange",
                  "Papaya (Raw)",
                  "Peas Wet",
                  "Pomegranate",
                  "Potato",
                  "Pumpkin",
                  "Raddish",
                  "Sweet Potato",
                  "Tinda",
                  "Water Melon",
                  "Soyabean",
                  "Cotton",
                  "Cummin Seed(Jeera)",
                  "Groundnut",
                  "Sesamum(Sesame",
                  "Gingelly",
                  "Til)",
                  "Wheat",
                  "Arhar (Tur/Red Gram)(Whole)",
                  "Bajra(Pearl Millet/Cumbu)",
                  "Green Gram (Moong)(Whole)",
                  "Kabuli Chana(Chickpeas-White)",
                  "Methi Seeds",
                  "Mustard",
                  "Castor Seed",
                  "Guar Seed(Cluster Beans Seed)",
                  "Isabgul (Psyllium)",
                  "Onion Green",
                  "Corriander Seed",
                  "Dry Chillies",
                  "Ground Nut Seed",
                  "Cluster Beans",
                  "Beetroot",
                  "Cowpea(Veg)",
                  "Drumstick",
                  "Elephant Yam (Suran)",
                  "French Beans (Frasbean)",
                  "Indian Beans (Seam)",
                  "Pegeon Pea (Arhar Fali)",
                  "Pointed Gourd (Parval)",
                  "Ridge Gourd(Tori)",
                  "Surat Beans (Papadi)",
                  "Turmeric (Raw)",
                  "Yam (Ratalu)",
                  "Spinach",
                  "Banana",
                  "Ber(Zizyphus/Borehannu)",
                  "Ginger(Dry)",
                  "Guava",
                  "Kinnow",
                  "Turnip",
                  "Leafy Vegetable",
                  "Papaya",
                  "Peas Cod",
                  "Pineapple",
                  "Mashrooms",
                  "Colacasia",
                  "Field Pea",
                  "Dalda",
                  "Mahua",
                  "Mustard Oil",
                  "Rice",
                  "Sugar",
                  "Wheat Atta",
                  "White Peas",
                  "Beans",
                  "Chapparad Avare",
                  "Chilly Capsicum",
                  "Green Avare (w)",
                  "Seemebadnekai",
                  "Snake Gourd",
                  "Suvarna Gadde",
                  "Sweet Pumpkin",
                  "Kulthi(Horse Gram)",
                  "Bunch Beans",
                  "Thondekai",
                  "Arecanut(Betelnut/Supari)",
                  "Tamarind Seed",
                  "Tamarind Fruit",
                  "Tender Coconut",
                  "Foxtail Millet(Navane)",
                  "Green Peas",
                  "Tapioca",
                  "Amphophalus",
                  "Ashgourd",
                  "Amaranthus",
                  "Mango",
                  "Black Pepper",
                  "Mango (Raw-Ripe)",
                  "Coconut",
                  "Rubber",
                  "Copra",
                  "Coconut Oil",
                  "Coconut Seed",
                  "Chili Red",
                  "Cowpea (Lobia/Karamani)",
                  "Lime",
                  "Pepper Ungarbled",
                  "Duster Beans",
                  "Coffee",
                  "Mint(Pudina)",
                  "Gur(Jaggery)",
                  "Chrysanthemum(Loose)",
                  "Marigold(Calcutta)",
                  "Betal Leaves",
                  "Hen",
                  "Jack Fruit",
                  "Fish",
                  "Amla(Nelli Kai)",
                  "Rat Tail Radish (Mogari)",
                  "Season Leaves",
                  "Squash(Chappal Kadoo)",
                  "Moath Dal",
                  "Taramira",
                  "Barley (Jau)",
                  "Soanf",
                  "Cashewnuts",
                  "T.v. Cumbu",
                  "Turmeric",
                  "Ragi (Finger Millet)",
                  "Paddy(Dhan)(Basmati)",
                  "Arhar Dal(Tur Dal)",
                  "Bengal Gram Dal (Chana Dal)",
                  "Black Gram Dal (Urd Dal)",
                  "Green Gram Dal (Moong Dal)",
                  "Lentil (Masur)(Whole)",
                "Masur Dal",
                  "Ghee",
                  "Peas(Dry)",
                  "Linseed",
                  "Jute"
                  ]

#print(list1)
list2=["टोमॅटो",
                  "काळी हरभरा (उडीद बीन्स) (संपूर्ण)",
                  "लिंबू",
                  "ज्वार (ज्वारी)",
                  "बंगाल ग्राम (ग्रॅम) (संपूर्ण)",
                  "धान (धान) (सामान्य)",
                  "मका",
                  "Appleपल",
                  "केळी - हिरवा",
                  "भिंडी (लेडीज फिंगर)",
                  "कारले",
                  "दुधीभोपळा",
                  "वांगे",
                  "कोबी",
                  "शिमला मिर्ची",
                  "गाजर",
                  "फुलकोबी",
                  "चिकू (सपोटा)",
                  "कोथिंबीरीची पाने)",
                  "कुकंबर (खीरा)",
                  "लसूण",
                  "आले (हिरवा)",
                  "द्राक्षे",
                  "हिरवी मिरची",
                  "ग्वार",
                  "कार्बुजा (कस्तुरी खरबूज)",
                  "नूल खोल",
                  "छोटा लौकी (कुंडरू)",
                  "मेथी (पाने)",
                  "मौसंबी (गोड चुना)",
                  "कांदा",
                  "ऑरेंज",
                  "पपई (रॉ)",
                  "वाटाणे ओले",
                  "डाळिंब",
                  "बटाटा",
                  "भोपळा",
                  "रॅडिश",
                  "रताळे",
                  "टिंडा",
                  "वॉटर खरबूज",
                  "सोयाबीन",
                  "कापूस",
                  "कमिन बियाणे (जीरा)",
                  "शेंगदाणा",
                  "तीळ (तीळ)",
                  "जिन्गली",
                  "तिल)",
                  "गहू",
                  "अरहर (तूर / लाल हरभरा) (संपूर्ण)",
                  "बाजरी (मोत्याची बाजरी / कुंबू)",
                  "ग्रीन ग्राम (मूग) (संपूर्ण)",
                  "काबुली चना (चिकन-व्हाइट)",
                  "मेथी बियाणे",
                  "मोहरी",
                  "एरंडेल बियाणे",
                  "ग्वार बियाणे (क्लस्टर बीन्स बियाणे)",
                  "इसाबगुल (सायलियम)",
                  "कांदा हिरवा",
                  "कोरीएंडर बियाणे",
                  "ड्राय मिरची",
                  "ग्राउंड नट बियाणे",
                  "क्लस्टर बीन्स",
                  "बीटरूट",
                  "काउपीया (वेज)",
                  "शेवगा",
                  "हत्ती याम (सुरण)",
                  "फ्रेंच बीन्स (फ्रासीबियन)",
                  "इंडियन बीन्स (सीम)",
                  "पेगॉन पे (अरहर फली)",
                  "पेन्टेड लौकी (परवल)",
                  "रिज लौकी (तोरी)",
                  "सूरत बीन्स (पापडी)",
                  "हळद (रॉ)",
                  "याम (रतालू)",
                  "पालक",
                  "केळी",
                  "बेर (झिजिफस / बोरहेन्नू)",
                  "आले (कोरडे)",
                  "पेरू",
                  "किन्नू",
                  "शलजम",
                  "पालेभाज्या",
                  "पपई",
                  "मटर कॉड",
                  "अननस",
                  "मशरूम",
                  "कोलाकासिया",
                  "फील्ड वाटाणा",
                  "डालडा",
                  "महुआ",
                  "मोहरीचे तेल",
                  "तांदूळ",
                  "साखर",
                  "गहू अट्टा",
                  "पांढरा वाटाणे",
                  "बीन्स",
                  "छप्परद अवारे",
                  "मिरची कॅप्सिकम",
                  "ग्रीन अवारे (डब्ल्यू)",
                  "सीमबदनेकाई",
                  "साप लौकी",
                  "सुवर्णा गडदे",
                  "गोड भोपळा",
                  "कुलथी (घोडा हरभरा)",
                  "गुच्छ बीन्स",
                  "थोंडेकाई",
                  "चिंचेची बियाणे",
                  "चिंचेचे फळ",
                  "निविदा नारळ",
                  "फॉक्सटेल बाजरी (नावणे)",
                  "मटार",
                  "तापिओका",
                  "अँफोफॅलस",
                  "Gशगॉर्ड",
                  "अमरानथुस",
                  "आंबा",
                  "काळी मिरी",
                  "आंबा (कच्चा-पिकलेला)",
                  "नारळ",
                  "रबर",
                  "कोपरा",
                  "खोबरेल तेल",
                  "नारळ बीज",
                  "काउपीया (लोबिया / करमणि)",
                  "चुना",
                  "पेपर अँगर्बल्ड",
                  "डस्टर बीन्स",
                  "कॉफी",
                  "पुदीना (पुदिना)",
                  "गुर (गूळ)",
                  "क्रायसॅन्थेमम (लूज)",
                  "मेरीगोल्ड (कलकत्ता)",
                  "बेटल पाने",
                  "कोंबडी",
                  "फणस",
                  "फिश",
                  "आमला (नेल्ली कै)",
                  "रॅट टेल मूली (मोगरी)",
                  "हंगामातील पाने",
                  "स्क्वॉश (चप्पल कडू)",
                  "मॉथ डाळ",
                  "तारामिरा",
                  "बार्ली (जौ)",
                  "Soanf",
                  "काजू",
                  "टी.व्ही. कुंबू",
                  "हळद",
                  "रागी (फिंगर बाजरी)",
                  "धान (धान) (बासमती)",
                  "अरहर दाल (तूर दल)",
                  "बंगाल ग्राम दल (चना दल)",
                  "ब्लॅक ग्राम डाळ (उडीद डाळ)",
                  "ग्रीन ग्राम डाळ (मूग डाळ)",
                  "मसूर (मसूर) (संपूर्ण)",
                  "मसूर दाल",
                  "घी",
                  "वाटाणे (ड्राय)",
                  "अलसी",
                  "जूट",
                  "टोमॅटो",
                  "टोमॅटो",
                  "काळी हरभरा (उडीद बीन्स) (संपूर्ण)",
                  "लिंबू",
                  "ज्वार (ज्वारी)",
                  "बंगाल ग्राम (ग्रॅम) (संपूर्ण)",
                  "धान (धान) (सामान्य)",
                  "मका",
                  "Appleपल",
                  "केळी - हिरवा",
                  "भिंडी (लेडीज फिंगर)",
                  "कारले",
                  "दुधीभोपळा",
                  "वांगे",
                  "कोबी",
                  "शिमला मिर्ची",
                  "गाजर",
                  "फुलकोबी",
                  "चिकू (सपोटा)",
                  "कोथिंबीरीची पाने)",
                  "कुकंबर (खीरा)",
                  "लसूण",
                  "आले (हिरवा)",
                  "द्राक्षे",
                  "हिरवी मिरची",
                  "",
                  "कार्बुजा (कस्तुरी खरबूज)",
                  "खोल",
                  "छोटा लौकी (कुंडरू)",
                  "मेथी (पाने)",
                  "मौसंबी (गोड चुना)",
                  "कांदा",
                  "ऑरेंज",
                  "पपई (रॉ)",
                  "वाटाणे ओले",
                  "डाळिंब",
                  "बटाटा",
                  "भोपळा",
                  "रॅडिश",
                  "रताळे",
                  "टिंडा",
                  "वॉटर खरबूज",
                  "सोयाबीन",
                  "कापूस",
                  "कमिन बियाणे (जीरा)",
                  "शेंगदाणा",
                  "तीळ (तीळ)",
                  "जिन्गली",
                  "तिल)",
                  "गहू",
                  "अरहर (तूर / लाल हरभरा) (संपूर्ण)",
                  "बाजरी (मोत्याची बाजरी / कुंबू)",
                  "ग्रीन ग्राम (मूग) (संपूर्ण)",
                  "काबुली चना (चिकन-व्हाइट)",
                  "मेथी बियाणे",
                  "मोहरी",
                  "एरंडेल बियाणे",
                  "ग्वार बियाणे (क्लस्टर बीन्स बियाणे)",
                  "इसाबगुल (सायलियम)",
                  "कांदा हिरवा",
                  "कोरीएंडर बियाणे",
                  "ड्राय मिरची",
                  "ग्राउंड नट बियाणे",
                  "क्लस्टर बीन्स",
                  "बीटरूट",
                  "काउपीया (वेज)",
                  "शेवगा",
                  "हत्ती याम (सुरण)",
                  "फ्रेंच बीन्स (फ्रासीबियन)",
                  "इंडियन बीन्स (सीम)",
                  "पेगॉन पे (अरहर फली)",
                  "पेन्टेड लौकी (परवल)",
                  "रिज लौकी (तोरी)",
                  "सूरत बीन्स (पापडी)",
                  "हळद (रॉ)",
                  "याम (रतालू)",
                  "पालक",
                  "केळी",
                  "बेर (झिजिफस / बोरहेन्नू)",
                  "आले (कोरडे)",
                  "पेरू",
                  "किन्नू",
                  "शलजम",
                  "पालेभाज्या",
                  "पपई",
                  "मटर कॉड",
                  "अननस",
                  "मशरूम",
                  "कोलाकासिया",
                  "फील्ड वाटाणा",
                  "डालडा",
                  "महुआ",
                  "मोहरीचे तेल",
                  "तांदूळ",
                  "साखर",
                  "गहू अट्टा",
                  "पांढरा वाटाणे",
                  "बीन्स",
                  "छप्परद अवारे",
                  "मिरची कॅप्सिकम",
                  "ग्रीन अवारे (डब्ल्यू)",
                  "सीमबदनेकाई",
                  "साप लौकी",
                  "सुवर्णा गडदे",
                  "गोड भोपळा",
                  "कुलथी (घोडा हरभरा)",
                  "गुच्छ बीन्स",
                  "थोंडेकाई",
                  "अरेकेनॉट (सुपारी / सुपारी)",
                  "चिंचेची बियाणे",
                  "चिंचेचे फळ",
                  "निविदा नारळ",
                  "फॉक्सटेल बाजरी (नावणे)",
                  "मटार",
                  "तापिओका",
                  "अँफोफॅलस",
                  "Gशगॉर्ड",
                  "अमरानथुस",
                  "आंबा",
                  "काळी मिरी",
                  "आंबा (कच्चा-पिकलेला)",
                  "नारळ",
                  "रबर",
                  "कोपरा",
                  "खोबरेल तेल",
                  "नारळ बीज",
                  "मिरची लाल",
                  "काउपीया (लोबिया / करमणि)",
                  "चुना",
                  "पेपर अँगर्बल्ड",
                  "डस्टर बीन्स",
                  "कॉफी",
                  "पुदीना (पुदिना)",
                  "गुर (गूळ)",
                  "क्रायसॅन्थेमम (लूज)",
                  "मेरीगोल्ड (कलकत्ता)",
                  "बेटल पाने",
                  "कोंबडी",
                  "फणस",
                  "फिश",
                  "आमला (नेल्ली कै)",
                  "रॅट टेल मूली (मोगरी)",
                  "हंगामातील पाने",
                  "स्क्वॉश (चप्पल कडू)",
                  "मॉथ डाळ",
                  "तारामिरा",
                  "बार्ली (जौ)",
                  "Soanf",
                  "काजू",
                  "टी.व्ही. कुंबू",
                  "हळद",
                  "रागी (फिंगर बाजरी)",
                  "धान (धान) (बासमती)",
                  "अरहर दाल (तूर दल)",
                  "बंगाल ग्राम दल (चना दल)",
                  "ब्लॅक ग्राम डाळ (उडीद डाळ)",
                  "ग्रीन ग्राम डाळ (मूग डाळ)",
                  "मसूर (मसूर) (संपूर्ण)",
                  "मसूर दाल",
                  "घी",
                  "वाटाणे (ड्राय)",
                  "अलसी",
                  "जूट"
                  ]
#print(list2)
#print(len(list1))
#print(len(list2))
dict1={}
for i  in range(len(list1)) :
   dict1[list1[i]]=list2[i]
   #dict1[list1[i]]="Amit"
   print(i)
#print(dict1)
print(len(dict1))
f = open("commodities.txt","w")
f.write(str(dict1))
f.close()